# manifest
apiVersion: v1
kind: Namespace
metadata:
  name: sbdemo-ap
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sbdemo-nfs-pvc
  namespace: sbdemo-ap
spec:
  # selector:
  #   matchLabels:
  #     role: nfs-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ap-config
  namespace: sbdemo-ap
data:
  SPRING_PROFILES_ACTIVE: "prd"
  DB_URL: "jdbc:postgresql://sbdemo-postgres-service.sbdemo-db:5432/demodb?user=postgres&password=postgres"
  PIC_DIR: "/opt/picDir"
  REDIS_HOST: "sbdemo-redis-service.sbdemo-redis"
  REDIS_PORT: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbdemo-apserver
  namespace: sbdemo-ap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sbdemo-apserver
  template:
    metadata:
      labels:
        app: sbdemo-apserver
    spec:
      containers:
        - name: apserver
          image: dayan888/springdemo:apserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
          envFrom:
            - configMapRef:
                name: ap-config
          volumeMounts:
            - mountPath: "/opt/picDir"
              name: apserver-pvc
      volumes:
        - name: apserver-pvc
          persistentVolumeClaim:
            claimName: sbdemo-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sbdemo-apserver-service
  namespace: sbdemo-ap
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: sbdemo-apserver