# manifest
apiVersion: v1
kind: Namespace
metadata:
  name: sbdemo-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbdemo-redis
  namespace: sbdemo-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbdemo-redis
  template:
    metadata:
      labels:
        app: sbdemo-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: sbdemo-redis-service
  namespace: sbdemo-redis
spec:
  type: ClusterIP
  ports:
    - name: "redis-port"
      protocol: "TCP"
      port: 6379
      targetPort: 6379
  selector:
    app: sbdemo-redis